#!/usr/bin/env python3
"""All-stages driver for the MACU render pipeline.

Usage:
    python3 run.py <slug>                  # run all stages, idempotent (cache-aware)
    python3 run.py <slug> --from <stage>   # restart from stage N (drops downstream cache)
    python3 run.py <slug> --only <stage>   # run a single stage and stop

Stages are numbered 1-8:
    1 vo    2 masters    3 rife    4 assemble
    5 music 6 whisper    7 srt     8 burn

Writes /tmp/macu_render_<slug>_report.json with timings + output paths.
"""
import sys, os, json, time, importlib.util, subprocess, glob, argparse

PIPELINE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, PIPELINE)
from lib import episode_paths, load_manifest

STAGES = [
    (1, "vo",       "stage_1_vo"),
    (2, "masters",  "stage_2_masters"),
    (3, "rife",     "stage_3_rife"),
    (4, "assemble", "stage_4_assemble"),
    (5, "music",    "stage_5_music"),
    (6, "whisper",  "stage_6_whisper"),
    (7, "srt",      "stage_7_srt"),
    (8, "burn",     "stage_8_burn"),
]

def load_stage(modname):
    spec = importlib.util.spec_from_file_location(modname, f"{PIPELINE}/{modname}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

def make_thumbs(slug):
    """7-up thumb strip at proportional times. Returns path."""
    p = episode_paths(slug)
    final = p["out_mp4"]
    out = p["out_thumbs"]
    r = subprocess.run(["ffprobe","-v","error","-show_entries","format=duration",
                        "-of","default=noprint_wrappers=1:nokey=1", final],
                       capture_output=True, text=True, check=True)
    dur = float(r.stdout.strip())
    # 7 stamps at 5%, 18%, 33%, 50%, 65%, 80%, 95%
    ts = [round(dur*frac) for frac in (0.05, 0.18, 0.33, 0.50, 0.65, 0.80, 0.95)]
    thumb_paths = []
    for t in ts:
        p_ = f"/tmp/macu_{slug}_thumb_{t}.jpg"
        subprocess.run(["ffmpeg","-y","-ss", str(t), "-i", final,
                        "-frames:v","1","-q:v","2", p_],
                       capture_output=True, check=True)
        thumb_paths.append(p_)
    # Tile via Pillow
    from PIL import Image, ImageDraw, ImageFont
    W, H, margin = 384, 384, 6
    canvas = Image.new("RGB", (len(ts)*W + (len(ts)+1)*margin, H + 56 + margin*2), (15,15,18))
    d = ImageDraw.Draw(canvas)
    try:
        bold = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 20)
        small = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 13)
    except Exception:
        bold = small = ImageFont.load_default()
    d.text((margin, 6), f"MACU {slug} — {os.path.basename(final)}", fill=(230,230,230), font=bold)
    d.text((margin, 32), "Generated by /macu-render", fill=(170,170,170), font=small)
    for i, (t, tp) in enumerate(zip(ts, thumb_paths)):
        if not os.path.exists(tp): continue
        im = Image.open(tp).convert("RGB").resize((W,H), Image.LANCZOS)
        x = margin + i*(W+margin)
        canvas.paste(im, (x, 56))
        d.rectangle([x, 56+H-22, x+W, 56+H], fill=(40,40,44))
        d.text((x+8, 56+H-20), f"t={t}s", fill=(220,220,220), font=small)
    canvas.save(out, "JPEG", quality=88)
    return out

_events_fp = None

def emit(kind, **payload):
    """Emit a structured event to --events-out (JSONL) if set. Also prints
    a one-line human form to stdout so plain CLI runs stay readable."""
    payload = {"ts": time.time(), "kind": kind, **payload}
    if _events_fp:
        _events_fp.write(json.dumps(payload) + "\n")
        _events_fp.flush()

def main():
    global _events_fp
    ap = argparse.ArgumentParser()
    ap.add_argument("slug")
    ap.add_argument("--from", dest="from_stage", type=int, default=1)
    ap.add_argument("--only", type=int, default=None)
    ap.add_argument("--events-out", default=None,
                    help="Append JSONL events to this path (one per stage + job-level)")
    args = ap.parse_args()
    slug = args.slug

    if args.events_out:
        _events_fp = open(args.events_out, "a", buffering=1)  # line-buffered

    # Sanity check: manifest must exist
    paths = episode_paths(slug)
    if not os.path.exists(paths["manifest"]):
        print(f"ERROR: manifest not found: {paths['manifest']}")
        emit("job.error", error=f"manifest not found: {paths['manifest']}")
        sys.exit(2)

    report = {"slug": slug, "stages": [], "started": time.time()}
    emit("job.started", slug=slug, from_stage=args.from_stage, only=args.only)
    t_total = time.time()
    for num, name, modname in STAGES:
        if args.only and num != args.only:
            continue
        if num < args.from_stage:
            continue
        print(f"\n=== stage {num} {name} ===")
        emit("stage.started", n=num, name=name)
        t0 = time.time()
        mod = load_stage(modname)
        try:
            result = mod.main(slug) or {}
        except Exception as e:
            elapsed = round(time.time()-t0, 2)
            report["stages"].append({"n": num, "name": name, "error": str(e),
                                     "wall_s": elapsed})
            print(f"!! stage {num} {name} FAILED ({elapsed}s): {e}")
            emit("stage.error", n=num, name=name, error=str(e), wall_s=elapsed)
            emit("job.error", error=f"stage {num} {name}: {e}")
            with open(f"/tmp/macu_render_{slug}_report.json","w") as f:
                json.dump(report, f, indent=2)
            sys.exit(1)
        elapsed = round(time.time()-t0, 2)
        result["n"] = num; result["name"] = name; result["wall_s"] = elapsed
        report["stages"].append(result)
        print(f"-- stage {num} {name} done in {elapsed}s")
        emit("stage.done", n=num, name=name, wall_s=elapsed, result=result)

    # Verify final
    final = paths["out_mp4"]
    if os.path.exists(final):
        thumbs = make_thumbs(slug)
        report["final"] = final
        report["thumbs"] = thumbs
        report["final_size_mb"] = round(os.path.getsize(final)/(1024*1024), 2)
        try:
            r = subprocess.run(["ffprobe","-v","error","-show_entries","format=duration",
                                "-of","default=noprint_wrappers=1:nokey=1", final],
                               capture_output=True, text=True, check=True)
            report["final_duration_s"] = round(float(r.stdout.strip()), 2)
        except Exception:
            pass
    report["total_wall_s"] = round(time.time()-t_total, 2)

    rep_path = f"/tmp/macu_render_{slug}_report.json"
    with open(rep_path, "w") as f:
        json.dump(report, f, indent=2)
    emit("job.done", final=final, thumbs=report.get("thumbs"),
         final_size_mb=report.get("final_size_mb"),
         final_duration_s=report.get("final_duration_s"),
         total_wall_s=report["total_wall_s"], report_path=rep_path)
    print(f"\nReport: {rep_path}")
    print(f"Final:  {final}")
    print(f"Total wall: {report['total_wall_s']}s")

if __name__ == "__main__":
    main()
