#!/usr/bin/env python3
"""agen_sfx.py — generate an SFX one-shot with `agen` (AudioGen), normalize it to the
MACU kit standard, and land it in assets/sfx/ with a provenance catalog row.

A third SFX acquisition route alongside freesound_fetch.py (CC0) and ffmpeg-lavfi synth.
`agen sfx` outputs 16 kHz mono — we re-normalize to 24 kHz / mono / PCM s16 / −3 dBFS by
reusing freesound_fetch.normalize(), so the kit stays uniform and manifest gain behaves.

Usage:
  agen_sfx.py "<prompt>" <basename> [--duration N] [--seed N] [--dest DIR]

  prompt        AudioGen text-to-foley prompt, e.g. "heavy iron door slam, dry, close mic"
  basename      output filename (no ext), e.g. "iron_door_slam"
  --duration    seconds (default 3.0)
  --seed        reproducible seed (default: derived from the prompt, so re-runs match)
  --dest        output dir (default: /mnt/storage/shares/MACU/assets/sfx)

Provenance: agen audio is de-novo / public-domain (local model, no third-party samples),
so it needs no license attribution — but the prompt + seed are logged so any clip can be
regenerated byte-for-similar. Returns 0 on success, non-zero on GPU-busy / generation error.
"""
import argparse
import hashlib
import pathlib
import subprocess
import sys
import tempfile

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from freesound_fetch import normalize  # reuse the kit normalize (24k mono s16, −3 dBFS)
import agen_lib

DEFAULT_DEST = pathlib.Path("/mnt/storage/shares/MACU/assets/sfx")


def _probe_dur(p: pathlib.Path) -> float:
    try:
        r = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", str(p)],
            capture_output=True, text=True, check=True,
        )
        return float(r.stdout.strip())
    except Exception:
        return 0.0


def _append_catalog(dest_dir: pathlib.Path, basename: str, dur: float, prompt: str, seed: int):
    readme = dest_dir / "README.md"
    if not readme.exists():
        return
    row = (f"| `{basename}.wav` | {dur:.2f}s | **agen sfx** (MACU-local, AudioGen) | "
           f"Public Domain (de novo) | prompt: \"{prompt}\" · seed {seed} |\n")
    readme.write_text(readme.read_text().rstrip("\n") + "\n" + row)


def _seed_for(prompt: str, override) -> int:
    if override is not None:
        return int(override)
    return int(hashlib.sha256(prompt.encode()).hexdigest(), 16) % 100000


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("prompt")
    ap.add_argument("basename")
    ap.add_argument("--duration", type=float, default=3.0)
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("--dest", default=str(DEFAULT_DEST))
    args = ap.parse_args()

    dest_dir = pathlib.Path(args.dest)
    dest_dir.mkdir(parents=True, exist_ok=True)
    out_path = dest_dir / f"{args.basename}.wav"
    if out_path.exists():
        print(f"already exists: {out_path}")
        return 0

    seed = _seed_for(args.prompt, args.seed)
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        tmp_path = pathlib.Path(tmp.name)
    try:
        try:
            agen_lib.run_agen("sfx", args.prompt, tmp_path, duration=args.duration, seed=seed)
        except RuntimeError as e:
            print(f"[agen_sfx] {e}")
            return 4  # GPU busy
        normalize(tmp_path, out_path)  # 16k → 24k mono s16, −3 dBFS, in one pass
        dur = _probe_dur(out_path)
        _append_catalog(dest_dir, args.basename, dur, args.prompt, seed)
        print(f"wrote {out_path} ({dur:.2f}s, seed {seed})")
    finally:
        if tmp_path.exists():
            tmp_path.unlink()
    return 0


if __name__ == "__main__":
    sys.exit(main())
