#!/usr/bin/env python3
"""All-stages driver for the MACU render pipeline.

Usage:
    python3 run.py <slug>                  # run all stages, idempotent (cache-aware)
    python3 run.py <slug> --from <stage>   # restart from stage N (drops downstream cache)
    python3 run.py <slug> --only <stage>   # run a single stage and stop

Stages are numbered 1-8:
    1 vo    2 masters    3 rife    4 assemble
    5 music 6 whisper    7 srt     8 burn

Writes /tmp/macu_render_<slug>_report.json with timings + output paths.
"""
import sys, os, json, time, importlib.util, subprocess, glob, argparse

PIPELINE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, PIPELINE)
from lib import episode_paths, load_manifest, set_progress_tick
import stackchan

STAGES = [
    (1, "vo",       "stage_1_vo"),
    (2, "masters",  "stage_2_masters"),
    (3, "rife",     "stage_3_rife"),
    (4, "assemble", "stage_4_assemble"),
    (5, "music",    "stage_5_music"),
    (6, "whisper",  "stage_6_whisper"),
    (7, "srt",      "stage_7_srt"),
    (8, "burn",     "stage_8_burn"),
]

def load_stage(modname):
    spec = importlib.util.spec_from_file_location(modname, f"{PIPELINE}/{modname}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

def make_thumbs(slug):
    """7-up thumb strip at proportional times. Returns path."""
    p = episode_paths(slug)
    final = p["out_mp4"]
    out = p["out_thumbs"]
    r = subprocess.run(["ffprobe","-v","error","-show_entries","format=duration",
                        "-of","default=noprint_wrappers=1:nokey=1", final],
                       capture_output=True, text=True, check=True)
    dur = float(r.stdout.strip())
    # 7 stamps at 5%, 18%, 33%, 50%, 65%, 80%, 95%
    ts = [round(dur*frac) for frac in (0.05, 0.18, 0.33, 0.50, 0.65, 0.80, 0.95)]
    thumb_paths = []
    for t in ts:
        p_ = f"/tmp/macu_{slug}_thumb_{t}.jpg"
        subprocess.run(["ffmpeg","-y","-ss", str(t), "-i", final,
                        "-frames:v","1","-q:v","2", p_],
                       capture_output=True, check=True)
        thumb_paths.append(p_)
    # Tile via Pillow
    from PIL import Image, ImageDraw, ImageFont
    W, H, margin = 384, 384, 6
    canvas = Image.new("RGB", (len(ts)*W + (len(ts)+1)*margin, H + 56 + margin*2), (15,15,18))
    d = ImageDraw.Draw(canvas)
    try:
        bold = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 20)
        small = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 13)
    except Exception:
        bold = small = ImageFont.load_default()
    d.text((margin, 6), f"MACU {slug} — {os.path.basename(final)}", fill=(230,230,230), font=bold)
    d.text((margin, 32), "Generated by /macu-render", fill=(170,170,170), font=small)
    for i, (t, tp) in enumerate(zip(ts, thumb_paths)):
        if not os.path.exists(tp): continue
        im = Image.open(tp).convert("RGB").resize((W,H), Image.LANCZOS)
        x = margin + i*(W+margin)
        canvas.paste(im, (x, 56))
        d.rectangle([x, 56+H-22, x+W, 56+H], fill=(40,40,44))
        d.text((x+8, 56+H-20), f"t={t}s", fill=(220,220,220), font=small)
    canvas.save(out, "JPEG", quality=88)
    return out

def make_youtube_thumb(slug):
    """Pull one still for the YouTube upload thumbnail from the wide intro card
    (titles/thumb_wide.mp4 @ 1920x1080), falling back to the square card
    (titles/thumb.mp4). Writes final/<slug>_thumb.png. Returns the path, or
    None if the episode has no thumb card."""
    p = episode_paths(slug)
    out = p["out_thumb_png"]
    wide = f"{p['titles']}/thumb_wide.mp4"
    square = f"{p['titles']}/thumb.mp4"
    if os.path.exists(wide):
        src, scale = wide, "1920:1080"
    elif os.path.exists(square):
        src, scale = square, "1024:1024"
    else:
        return None
    subprocess.run(["ffmpeg", "-y", "-ss", "1.0", "-i", src,
                    "-frames:v", "1", "-vf", f"scale={scale}", "-q:v", "2", out],
                   capture_output=True, check=True)
    return out

_events_fp = None

def emit(kind, **payload):
    """Emit a structured event to --events-out (JSONL) if set. Also prints
    a one-line human form to stdout so plain CLI runs stay readable."""
    payload = {"ts": time.time(), "kind": kind, **payload}
    if _events_fp:
        _events_fp.write(json.dumps(payload) + "\n")
        _events_fp.flush()

def main():
    global _events_fp
    ap = argparse.ArgumentParser()
    ap.add_argument("slug")
    ap.add_argument("--from", dest="from_stage", type=int, default=1)
    ap.add_argument("--only", type=int, default=None)
    ap.add_argument("--dub", default=None, metavar="LANG",
                    help="Dub mode: localize an already-rendered episode into LANG "
                         "(re-VO + remux + translated subs; skips stages 2-3).")
    ap.add_argument("--engine", default="qwen", choices=["qwen", "argos"],
                    help="Translation engine for --dub (default qwen).")
    ap.add_argument("--subs-only", action="store_true",
                    help="With --dub: produce translated subtitles only, no dubbed audio.")
    ap.add_argument("--events-out", default=None,
                    help="Append JSONL events to this path (one per stage + job-level)")
    ap.add_argument("--no-stackchan", action="store_true",
                    help="Disable StackChan LED progress bar (also via MACU_NO_STACKCHAN env var)")
    args = ap.parse_args()
    slug = args.slug

    if args.events_out:
        _events_fp = open(args.events_out, "a", buffering=1)  # line-buffered

    # StackChan LED progress bar: opt-out via flag/env, auto-skip if device unreachable.
    stackchan_on = not (args.no_stackchan or os.environ.get("MACU_NO_STACKCHAN"))
    if stackchan_on:
        stackchan_on = stackchan.reachable()
        if not stackchan_on:
            print("[stackchan] unreachable, LED progress disabled for this run")
    stackchan.set_enabled(stackchan_on)
    set_progress_tick(lambda n, name, frac: stackchan.paint(n, frac))

    # Sanity check: manifest must exist
    paths = episode_paths(slug)
    if not os.path.exists(paths["manifest"]):
        print(f"ERROR: manifest not found: {paths['manifest']}")
        emit("job.error", error=f"manifest not found: {paths['manifest']}")
        sys.exit(2)

    # Dub mode bypasses the 8-stage loop: localize an already-rendered episode.
    if args.dub:
        import dub
        emit("job.started", slug=slug, dub=args.dub, engine=args.engine, subs_only=args.subs_only)
        rc = dub.run_dub(slug, args.dub, args.engine, subs_only=args.subs_only, emit=emit)
        sys.exit(rc)

    report = {"slug": slug, "stages": [], "started": time.time()}
    emit("job.started", slug=slug, from_stage=args.from_stage, only=args.only)
    t_total = time.time()
    job_failed = False
    try:
        for num, name, modname in STAGES:
            if args.only and num != args.only:
                continue
            if num < args.from_stage:
                continue
            print(f"\n=== stage {num} {name} ===")
            emit("stage.started", n=num, name=name)
            stackchan.paint(num, 0.0)
            t0 = time.time()
            mod = load_stage(modname)
            try:
                result = mod.main(slug) or {}
            except Exception as e:
                elapsed = round(time.time()-t0, 2)
                report["stages"].append({"n": num, "name": name, "error": str(e),
                                         "wall_s": elapsed})
                print(f"!! stage {num} {name} FAILED ({elapsed}s): {e}")
                emit("stage.error", n=num, name=name, error=str(e), wall_s=elapsed)
                emit("job.error", error=f"stage {num} {name}: {e}")
                with open(f"/tmp/macu_render_{slug}_report.json","w") as f:
                    json.dump(report, f, indent=2)
                stackchan.paint_error(num)
                time.sleep(2)  # let the user see which zone failed before clear
                job_failed = True
                sys.exit(1)
            elapsed = round(time.time()-t0, 2)
            result["n"] = num; result["name"] = name; result["wall_s"] = elapsed
            report["stages"].append(result)
            print(f"-- stage {num} {name} done in {elapsed}s")
            emit("stage.done", n=num, name=name, wall_s=elapsed, result=result)
            stackchan.paint(num, 1.0)
    finally:
        if job_failed:
            stackchan.clear()
        # success path clears after the celebratory hold below

    # Verify final
    final = paths["out_mp4"]
    if os.path.exists(final):
        report["final"] = final
        # Thumb strip needs Pillow; never fail a finished render over it (mirrors
        # the make_youtube_thumb guard right below).
        try:
            report["thumbs"] = make_thumbs(slug)
        except Exception as e:
            print(f"[thumbs] skipped: {e}")
        try:
            yt = make_youtube_thumb(slug)
            if yt:
                report["youtube_thumb"] = yt
                print(f"YouTube thumb: {yt}")
        except Exception as e:
            print(f"[youtube thumb] skipped: {e}")
        report["final_size_mb"] = round(os.path.getsize(final)/(1024*1024), 2)
        try:
            r = subprocess.run(["ffprobe","-v","error","-show_entries","format=duration",
                                "-of","default=noprint_wrappers=1:nokey=1", final],
                               capture_output=True, text=True, check=True)
            report["final_duration_s"] = round(float(r.stdout.strip()), 2)
        except Exception:
            pass
    report["total_wall_s"] = round(time.time()-t_total, 2)

    rep_path = f"/tmp/macu_render_{slug}_report.json"
    with open(rep_path, "w") as f:
        json.dump(report, f, indent=2)
    emit("job.done", final=final, thumbs=report.get("thumbs"),
         youtube_thumb=report.get("youtube_thumb"),
         final_size_mb=report.get("final_size_mb"),
         final_duration_s=report.get("final_duration_s"),
         total_wall_s=report["total_wall_s"], report_path=rep_path)
    print(f"\nReport: {rep_path}")
    print(f"Final:  {final}")
    print(f"Total wall: {report['total_wall_s']}s")

    # Celebratory hold: only on a full render that produced final/<slug>.mp4.
    # Partial runs (--from N, --only N) leave the last-painted state so August
    # can see how far it got. He can clear manually via the MCP set_buffer tool.
    if os.path.exists(final):
        stackchan.paint_all_done()
        time.sleep(3)
        stackchan.clear()

if __name__ == "__main__":
    main()
